"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import dateutil.parser
from dataclasses_json import Undefined, dataclass_json
from datetime import datetime
from enum import Enum
from marshmallow import fields
from sdk import utils
from typing import Optional

class OxygenSaturationSampleTypeEnum(str, Enum):
    r"""Type of oxygen saturation measurement (i.e. blood vs muscle)"""
    BLOOD = 'BLOOD'
    MUSCLE = 'MUSCLE'


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class OxygenSaturationSample:
    
    percentage: Optional[float] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('percentage'), 'exclude': lambda f: f is None }})
    r"""User's oxygen saturation percentage - referring to either SpO2 or SmO2, based on the `type` field"""  
    timestamp: Optional[datetime] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('timestamp'), 'encoder': utils.datetimeisoformat(True), 'decoder': dateutil.parser.isoparse, 'mm_field': fields.DateTime(format='iso'), 'exclude': lambda f: f is None }})
    r"""Time with which the record is associated, in ISO8601 format with microsecond precision. TimeZone info will be provided whenever possible. If absent, the time corresponds to the user's local time"""  
    type: Optional[OxygenSaturationSampleTypeEnum] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('type'), 'exclude': lambda f: f is None }})
    r"""Type of oxygen saturation measurement (i.e. blood vs muscle)"""  
    