"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

import requests as requests_http
from . import utils
from sdk.models import operations
from typing import Any, Optional

class Nutrition:
    r"""Nutrition data"""
    _client: requests_http.Session
    _security_client: requests_http.Session
    _server_url: str
    _language: str
    _sdk_version: str
    _gen_version: str

    def __init__(self, client: requests_http.Session, security_client: requests_http.Session, server_url: str, language: str, sdk_version: str, gen_version: str) -> None:
        self._client = client
        self._security_client = security_client
        self._server_url = server_url
        self._language = language
        self._sdk_version = sdk_version
        self._gen_version = gen_version
        
    def delete(self, request: operations.DeleteNutritionRequest) -> operations.DeleteNutritionResponse:
        r"""Delete nutrition data from account
        Used to delete nutrition logs the user has registered on their account
        """
        base_url = self._server_url
        
        url = base_url.removesuffix('/') + '/nutrition'
        
        headers = {}
        req_content_type, data, form = utils.serialize_request_body(request, "request_body", 'json')
        if req_content_type not in ('multipart/form-data', 'multipart/mixed'):
            headers['content-type'] = req_content_type
        if data is None and form is None:
            raise Exception('request body is required')
        query_params = utils.get_query_params(operations.DeleteNutritionRequest, request)
        
        client = self._security_client
        
        http_res = client.request('DELETE', url, params=query_params, data=data, files=form, headers=headers)
        content_type = http_res.headers.get('Content-Type')

        res = operations.DeleteNutritionResponse(status_code=http_res.status_code, content_type=content_type, raw_response=http_res)
        
        if http_res.status_code == 200:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[operations.DeleteNutrition200ApplicationJSON])
                res.delete_nutrition_200_application_json_object = out
        elif http_res.status_code == 207:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[operations.DeleteNutrition207ApplicationJSON])
                res.delete_nutrition_207_application_json_object = out
        elif http_res.status_code == 400:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[operations.DeleteNutrition400ApplicationJSON])
                res.delete_nutrition_400_application_json_object = out
        elif http_res.status_code == 401:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[operations.DeleteNutrition401ApplicationJSON])
                res.delete_nutrition_401_application_json_object = out
        elif http_res.status_code == 403:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[operations.DeleteNutrition403ApplicationJSON])
                res.delete_nutrition_403_application_json_object = out
        elif http_res.status_code == 404:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[operations.DeleteNutrition404ApplicationJSON])
                res.delete_nutrition_404_application_json_object = out

        return res

    def get(self, request: operations.GetNutritionRequest) -> operations.GetNutritionResponse:
        r"""Get nutrition data from account"""
        base_url = self._server_url
        
        url = base_url.removesuffix('/') + '/nutrition'
        
        query_params = utils.get_query_params(operations.GetNutritionRequest, request)
        
        client = self._security_client
        
        http_res = client.request('GET', url, params=query_params)
        content_type = http_res.headers.get('Content-Type')

        res = operations.GetNutritionResponse(status_code=http_res.status_code, content_type=content_type, raw_response=http_res)
        
        if http_res.status_code == 200:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[Any])
                res.get_nutrition_200_application_json_one_of = out
        elif http_res.status_code == 400:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[operations.GetNutrition400ApplicationJSON])
                res.get_nutrition_400_application_json_object = out
        elif http_res.status_code == 401:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[operations.GetNutrition401ApplicationJSON])
                res.get_nutrition_401_application_json_object = out
        elif http_res.status_code == 403:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[operations.GetNutrition403ApplicationJSON])
                res.get_nutrition_403_application_json_object = out
        elif http_res.status_code == 404:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[operations.GetNutrition404ApplicationJSON])
                res.get_nutrition_404_application_json_object = out

        return res

    def send_provider(self, request: operations.PostNutritionRequestBody) -> operations.PostNutritionResponse:
        r"""Send nutrition data to data provider
        Used to post nutrition logs to a provider. Available for Fitbit
        """
        base_url = self._server_url
        
        url = base_url.removesuffix('/') + '/nutrition'
        
        headers = {}
        req_content_type, data, form = utils.serialize_request_body(request, "request", 'json')
        if req_content_type not in ('multipart/form-data', 'multipart/mixed'):
            headers['content-type'] = req_content_type
        if data is None and form is None:
            raise Exception('request body is required')
        
        client = self._security_client
        
        http_res = client.request('POST', url, data=data, files=form, headers=headers)
        content_type = http_res.headers.get('Content-Type')

        res = operations.PostNutritionResponse(status_code=http_res.status_code, content_type=content_type, raw_response=http_res)
        
        if http_res.status_code == 201:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[operations.PostNutrition201ApplicationJSON])
                res.post_nutrition_201_application_json_object = out
        elif http_res.status_code == 400:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[operations.PostNutrition400ApplicationJSON])
                res.post_nutrition_400_application_json_object = out
        elif http_res.status_code == 403:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[operations.PostNutrition403ApplicationJSON])
                res.post_nutrition_403_application_json_object = out
        elif http_res.status_code == 404:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[operations.PostNutrition404ApplicationJSON])
                res.post_nutrition_404_application_json_object = out

        return res

    